name: Docker build

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Checkout release tag
        uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

      - name: Build and push latest release
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: VERSION=${{ env.APP_VERSION }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.APP_VERSION }},${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
